apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: sonarqube
    releaseName: sonarqube
    repo: https://SonarSource.github.io/helm-chart-sonarqube
    namespace: sonarqube
    version: 6.0.1+425
